### ISSUE TITLE
Error in running exper.py example command

### ISSUE THREAD

**Issue by HasanShaukat** [ozanarkancan/char-ner#4]
I'm using Ubuntu 18.10 and installed the dependencies using pip3. When I run the example command:
`python3 src/exper.py --activation bi-lstm --n_hidden 128 128 --drates .2 .5 .8 --lang cze`

I get the following error:

`WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "exper.py", line 12, in <module>
    from dataset import Dset
  File "/home/hasan/Documents/char-ner/src/dataset.py", line 4, in <module>
    import rep
  File "/home/hasan/Documents/char-ner/src/rep.py", line 59
    print ' '.join(map(('{:^%d}'%mlen).format, [a[ci] for ci in cil] + [a[si]]))
            ^
SyntaxError: invalid syntax`

**Comment by ozanarkancan** [comment]
Hi,

It might be related with the python version. Can you give it a shot with python 2?

**Comment by HasanShaukat** [comment]
When trying with python2, I am getting the following error. I am using Ubuntu 18.10 and latest numpy and theano in python2.

Traceback (most recent call last):
  File "src/exper.py", line 249, in <module>
    main()
  File "src/exper.py", line 234, in main
    rdnn = RNN(feat.NC, feat.NF, args)
  File "/home/hasan/Documents/char-ner/src/lazrnn.py", line 212, in __init__
    cost_train = cost(lasagne.layers.get_output(l_out, deterministic=False))
  File "/home/hasan/.local/lib/python2.7/site-packages/lasagne/layers/helper.py", line 197, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/home/hasan/.local/lib/python2.7/site-packages/lasagne/layers/noise.py", line 102, in get_output_for
    dtype=input.dtype)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 901, in binomial
    x = self.uniform(size=size, nstreams=nstreams, **kwargs)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 872, in uniform
    rstates = self.get_substream_rstates(nstreams, dtype)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/configparser.py", line 117, in res
    return f(*args, **kwargs)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 779, in get_substream_rstates
    multMatVect(rval[0], A1p72, M1, A2p72, M2)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 62, in multMatVect
    [A_sym, s_sym, m_sym, A2_sym, s2_sym, m2_sym], o, profile=False)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/gof/vm.py", line 1084, in make_all
    impl=impl))
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1300, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/hasan/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1379, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', DotModulo(A, s, m, A2, s2, m2), '\n', "'module' object has no attribute '_get_ndarray_c_version'")

**Comment by ozanarkancan** [comment]
Since the code is 3 years old, it is best to use the dependencies with their exact versions:

```
numpy==1.11.2
scipy==0.18.1
scikit-learn==0.17.1
tabulate==0.7.5
Theano==1.0
```
